#include <stdarg.h>
#include "io.h"
#include "malloc.h"
#include "serial.h"
#include "strings.h"
//#include //"strings.h"

#define COM1 0x3f8

static void com1_write(char c) {
    //while (inb(COM1 + 5) & 0x20 == 0) // Wait until transmitter holding register is empty and ready for data
    while ((inb(COM1 + 5) & 0x20) == 0) // Wait until transmitter holding register is empty and ready for data
        ;

    // Qemu's serial port display interprets control characters, but \n just drops down a line, so we want a
    //   carriage return as well;
    if (c == '\n')
        outb(COM1, '\r');

    outb(COM1, c);
}

void com1_print(char* s) {
    while (*s != 0)
        com1_write(*s++);
}

/*
// #define VARIADIC_PRINT(p) void p##f(char* fmt, ...) {
//     va_list ap;        \
//     va_start(ap, fmt);             \
//     char* s = M_vsprintf(fmt, ap); \
//     va_end(ap); \
//     p(s); \
//     free(s); \
// }

//VARIADIC_PRINT(com1_print)
*/

// Can this be generated by a macro in strings.h?
// So just VARIADIC(print_com1)
// Seems pretty easy other than wantin the f in the middle
// Maybe it's okay to just tack the f at the end?  print_com1f(
// Or change my naming scheme to com1_write, com1_print, com1_printf...
// I guess I'm likely okay with that...
//void com1_printf(

// void printf_com1(char* s, ...) {
//     printf(print_com1, s, ...);// However you pass along varargs
//     // Calls printf (from strings) with
// }

// OR -- how about we let it just generate the body for us!

void com1_printf(char* fmt, ...) {
    VARIADIC_PRINT(com1_print);
}
